//! Shell completions and the man page, written from [`super::spec`].
//!
//! Generated from the same table as the parser rather than pulled from a
//! library, which keeps two dependencies and a few hundred kilobytes of
//! binary out of an app whose whole argument is that it is fast and small.
//! The shapes here are plain enough that the table is the hard part, and the
//! table already exists.
//!
//! The package runs the built binary to produce these, so they cannot be
//! generated from a different version of the surface than the one installed.

use super::spec::{self, Noun, LAUNCH, SURFACE};

pub fn script(shell: &str) -> String {
    match shell {
        "zsh" => zsh(),
        "fish" => fish(),
        _ => bash(),
    }
}

fn nouns() -> String {
    SURFACE.iter().map(|n| n.name).collect::<Vec<_>>().join(" ")
}

fn verbs(noun: &Noun) -> String {
    noun.verbs.iter().map(|v| v.name).collect::<Vec<_>>().join(" ")
}

fn bash() -> String {
    let mut out = String::from(
        "# omacharts completion for bash. Generated by `omacharts surface --completions bash`.\n\
         _omacharts() {\n  local cur prev\n  COMPREPLY=()\n  \
         cur=\"${COMP_WORDS[COMP_CWORD]}\"\n  prev=\"${COMP_WORDS[1]}\"\n\n  \
         if [ \"$COMP_CWORD\" -eq 1 ]; then\n    \
         COMPREPLY=( $(compgen -W \"",
    );
    out.push_str(&nouns());
    out.push_str(" help surface --help --version");
    for option in LAUNCH {
        out.push_str(&format!(" --{}", option.long));
    }
    out.push_str("\" -- \"$cur\") )\n    return\n  fi\n\n  case \"$prev\" in\n");
    // A launch option's own values, so `--provider <tab>` offers the feeds
    // rather than the files in the current directory.
    for option in LAUNCH {
        let values = spec::launch_values(option.long);
        if values.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "    --{})\n      COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") )\n      ;;\n",
            option.long,
            values.join(" ")
        ));
    }
    for noun in SURFACE {
        out.push_str(&format!("    {})\n      COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") )\n      ;;\n", noun.name, verbs(noun)));
    }
    out.push_str("  esac\n}\ncomplete -F _omacharts omacharts\n");
    out
}

/// A description, safe inside the single quotes zsh wants around it.
///
/// An apostrophe in a `_describe` entry ends the string it is in and leaves
/// the rest of the file as syntax nobody wrote — and a completion script that
/// does not parse takes every command's completion down with it, not just the
/// one whose help happened to say "Claude's". The table is prose written for
/// people, so an apostrophe in it is a matter of time rather than a mistake.
fn zsh_quoted(text: &str) -> String {
    text.replace('\'', "'\\''")
}

fn zsh() -> String {
    let mut out = String::from(
        "#compdef omacharts\n# Generated by `omacharts surface --completions zsh`.\n\
         _omacharts() {\n  local -a nouns\n  nouns=(\n",
    );
    for noun in SURFACE {
        out.push_str(&format!("    '{}:{}'\n", noun.name, zsh_quoted(noun.about)));
    }
    out.push_str("  )\n  local -a launch\n  launch=(\n");
    for option in LAUNCH {
        out.push_str(&format!("    '--{}:{}'\n", option.long, zsh_quoted(option.help)));
    }
    out.push_str(
        "  )\n  if (( CURRENT == 2 )); then\n    _describe 'command' nouns\n             _describe 'option' launch\n    return\n  fi\n  case \"${words[2]}\" in\n",
    );
    for option in LAUNCH {
        let values = spec::launch_values(option.long);
        if values.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "    --{})\n      _values '{}' {}\n      ;;\n",
            option.long,
            option.value,
            values.join(" ")
        ));
    }
    for noun in SURFACE {
        out.push_str(&format!("    {})\n      local -a verbs\n      verbs=(\n", noun.name));
        for verb in noun.verbs {
            out.push_str(&format!("        '{}:{}'\n", verb.name, zsh_quoted(verb.about)));
        }
        out.push_str("      )\n      _describe 'subcommand' verbs\n      ;;\n");
    }
    out.push_str("  esac\n}\n_omacharts \"$@\"\n");
    out
}

fn fish() -> String {
    let mut out =
        String::from("# Generated by `omacharts surface --completions fish`.\n");
    for option in LAUNCH {
        let values = spec::launch_values(option.long);
        out.push_str(&format!(
            "complete -c omacharts -l {} -d '{}' -x -a '{}'\n",
            option.long,
            option.help.replace('\'', ""),
            values.join(" ")
        ));
    }
    for noun in SURFACE {
        out.push_str(&format!(
            "complete -c omacharts -n __fish_use_subcommand -a {} -d '{}'\n",
            noun.name,
            noun.about.replace('\'', "")
        ));
        for verb in noun.verbs {
            out.push_str(&format!(
                "complete -c omacharts -n '__fish_seen_subcommand_from {}' -a {} -d '{}'\n",
                noun.name,
                verb.name,
                verb.about.replace('\'', "")
            ));
        }
    }
    out
}

/// The man page, in roff.
pub fn man() -> String {
    let mut out = format!(
        ".TH OMACHARTS 1 \"\" \"omacharts {}\" \"User Commands\"\n\
         .SH NAME\nomacharts \\- fast, beautiful charting software for Omarchy\n\
         .SH SYNOPSIS\n.B omacharts\n[\\fISYMBOL\\fR]\n.br\n.B omacharts\n\
         \\fICOMMAND\\fR \\fISUBCOMMAND\\fR [\\fIARGUMENTS\\fR]\n\
         .SH DESCRIPTION\nEverything the window can do can be done from here. A command\n\
         changing anything takes effect in a window that is already open,\n\
         straight away.\n.PP\nWith nothing running, the same commands work against the stored\n\
         data, so this is usable over ssh and out of a script.\n",
        env!("CARGO_PKG_VERSION")
    );
    out.push_str(".SH OPTIONS\n");
    for option in LAUNCH {
        out.push_str(&format!(
            ".TP\n.BI \\-\\-{} \\ {}\n{}\n",
            option.long, option.value, option.help
        ));
        let values = spec::launch_values(option.long);
        if !values.is_empty() {
            out.push_str(&format!(".br\nOne of: {}\n", values.join(", ")));
        }
    }
    out.push_str(".SH COMMANDS\n");
    for noun in SURFACE {
        out.push_str(&format!(".SS {}\n{}\n", noun.name, noun.about));
        for verb in noun.verbs {
            out.push_str(&format!(
                ".TP\n.B omacharts {} {}\n{}\n.br\nExample: \\fB{}\\fR\n",
                noun.name, verb.name, verb.about, verb.example
            ));
        }
    }
    out.push_str(".SH EXIT STATUS\n");
    for (code, meaning) in super::EXIT_CODES {
        out.push_str(&format!(".TP\n.B {code}\n{meaning}\n"));
    }
    out.push_str(
        ".SH SEE ALSO\nThe full command surface as JSON, for anything driving this from a\n\
         script:\n.PP\n.B omacharts surface --json\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A completion naming a command the parser does not have sends people
    /// down a dead end, which is worse than no completion at all.
    #[test]
    fn every_shell_offers_every_command() {
        for shell in ["bash", "zsh", "fish"] {
            let text = script(shell);
            for noun in SURFACE {
                assert!(text.contains(noun.name), "{shell} is missing {}", noun.name);
                for verb in noun.verbs {
                    assert!(
                        text.contains(verb.name),
                        "{shell} is missing {} {}",
                        noun.name,
                        verb.name
                    );
                }
            }
        }
    }

    /// A launch option nobody's shell will complete is an option nobody
    /// finds. The feeds it accepts are offered too, because the whole reason
    /// this replaced an environment variable is that a shell can offer it.
    #[test]
    fn every_shell_offers_every_launch_option_and_its_values() {
        for shell in ["bash", "zsh", "fish"] {
            let text = script(shell);
            for option in LAUNCH {
                // fish spells a long option without its dashes.
                let spelling = match shell {
                    "fish" => format!("-l {}", option.long),
                    _ => format!("--{}", option.long),
                };
                assert!(
                    text.contains(&spelling),
                    "{shell} is missing {spelling}"
                );
                for value in spec::launch_values(option.long) {
                    assert!(text.contains(value), "{shell} does not offer {value}");
                }
            }
        }
    }

    /// An apostrophe in a command's help must not end the zsh string it is
    /// quoted inside. A description reading "Claude's skills directory" did,
    /// and the whole script stopped parsing — every completion gone, not only
    /// that one. Counted rather than read back by zsh, which may not be on
    /// the machine running this.
    #[test]
    fn an_apostrophe_in_a_description_does_not_break_the_zsh_script() {
        let quotes = zsh().replace("'\\''", "").matches('\'').count();
        assert_eq!(quotes % 2, 0, "the zsh script has an unbalanced quote");

        let faked = zsh_quoted("Claude's own directory");
        assert_eq!(faked, "Claude'\\''s own directory");
        assert_eq!(faked.replace("'\\''", "").matches('\'').count(), 0);
    }

    #[test]
    fn the_man_page_documents_every_command_and_every_exit_code() {
        let page = man();
        for noun in SURFACE {
            for verb in noun.verbs {
                assert!(
                    page.contains(&format!("omacharts {} {}", noun.name, verb.name)),
                    "the man page is missing {} {}",
                    noun.name,
                    verb.name
                );
            }
        }
        for (code, _) in super::super::EXIT_CODES {
            assert!(page.contains(&format!(".B {code}\n")), "no exit status {code}");
        }
        for option in LAUNCH {
            assert!(page.contains(&format!("\\-\\-{}", option.long)), "{page}");
        }
    }
}
